services:
  weaviate:
    image: semitechnologies/weaviate:1.30.0
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - QUERY_DEFAULTS_LIMIT=100
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - ENABLE_MODULES=text2vec-transformers
      - TRANSFORMERS_INFERENCE_API=http://transformers:8000
      - CLUSTER_HOSTNAME=weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate
    depends_on:
      transformers:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 180s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    environment:
      - ENABLE_CUDA=0
      - MODEL_NAME=sentence-transformers/all-MiniLM-L6-v2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 180s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.rest
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - REST_API_KEY=${REST_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CG_API_KEY=${CG_API_KEY}
      - SANTIMENT_API_KEY=${SANTIMENT_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      weaviate:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 60s

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.ws
    ports:
      - "8765:8765"
      - "8002:8001"
    environment:
      - WS_API_KEY=${WS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      weaviate:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 60s

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
      - "8003:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      weaviate:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 20s
      retries: 15
      start_period: 60s

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.rest
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info", "--concurrency=4"]
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CG_API_KEY=${CG_API_KEY}
      - SANTIMENT_API_KEY=${SANTIMENT_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      redis:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "tasks", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 60s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s

  grafana:
    image: grafana/grafana:9.5.3
    volumes:
      - ./monitoring/grafana:/etc/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  weaviate_data:
  redis_data:
